### PR TITLE
[WIP] Support honeypot validation on Civi forms that are accessible to anonymous users

### PR DESCRIPTION
**Pull request by monishdeb**

### CODE REVIEW

**Comment by elisseck** [comment]
Hi Monish - thanks for the contribution!

I'm going to merge this because it's working for me and it adds some functionality where we had none before. I do think at some point we should have parity between event features and contribution features so it doesn't confuse people.

Right now it looks like we have "on for all forms", "on for some contribution forms and no event forms", "off for all forms". At some future point we probably want to add "on for some event forms and no contribution forms" to have parity. It doesn't feel important to me right away though.

Thoughts?

**Comment by elisseck** [comment]
Actually - I see you changed the title to [WIP] - should I wait to merge?

**Comment by monishdeb** [comment]
@elisseck as Joe has indicated there are some other online forms which are accessible to anonymous users. So I am going to support the validation for those forms too, the reason why I marked it with [WIP]. Will ask ya for review after I include the remaining fixes.

**Comment by elisseck** [comment]
There are a bunch of conflicts now and i'm not 100% sure what the thought process was behind this one so i'm going to close for now. Feel free to re-open if there is still interest.

**Pull request closed without merging**
