### PR TITLE
Australian Greens changes

### PR DESCRIPTION
**Pull request by seamuslee001**
- Update to use the latest civix,
- namespace all settings putting honeypot_ infront of them
- make all settings apply to every domain whenever set and clear cache after saving settings.
- Add in extension upgrade step to migrate settings to new namespace

### CODE REVIEW

**Comment by elisseck** [comment]
Hi Seamus,

Just wanted to say i've seen this and thanks for making a contribution!

Since I didn't have any time to write tests for this previously... it's going to take me awhile to get to it - but at a cursory glance looks good to me.

**Comment by MegaphoneJon** [comment]
This upgrade didn't keep my old settings - I don't know why, and I'm not particularly fussed, but I just thought I'd mention it.

**Comment by elisseck** [comment]
@MegaphoneJon Thanks for that report! I believe this PR renamed all of the settings for better compatibility with multi-site setups.

I remember thinking the upgrade path number was a little suspicious, but I don't know a huge amount about how you need to number upgrade fxns... I just remember someone telling me it's important and I have a feeling it just didn't run :). I'll take a look into it soon(tm). Could be significant for someone who dumped a huge array of IP ranges into that setting for whatever reason.

**Comment by MegaphoneJon** [comment]
FWIW the upgrade DID run, and I happened to test on a multi-site instance.

**Pull request merged**
